# 넘파이 미적분 

        https://qiita.com/jabberwocky0139/items/57637c1368ea1ebc9b45

In [1]:
import numpy as np

In [19]:
x = np.linspace(0,10)
dx = x[1]-x[0]
y = x**2 + 1
dydx = np.gradient(y, dx)

In [20]:
def f(x) :
    return x**2 + 1

In [21]:
diff__ = []
for i in x:
    diff__.append((f(i + dx) - f(i)) / dx)

In [22]:
diff__

[0.2040816326530616,
 0.6122448979591837,
 1.0204081632653057,
 1.4285714285714288,
 1.836734693877551,
 2.244897959183673,
 2.653061224489796,
 3.0612244897959195,
 3.4693877551020402,
 3.8775510204081636,
 4.285714285714291,
 4.693877551020401,
 5.102040816326529,
 5.510204081632647,
 5.918367346938783,
 6.326530612244894,
 6.734693877551012,
 7.142857142857132,
 7.551020408163276,
 7.9591836734693775,
 8.367346938775496,
 8.775510204081632,
 9.18367346938775,
 9.591836734693853,
 9.99999999999999,
 10.408163265306126,
 10.816326530612226,
 11.224489795918345,
 11.632653061224465,
 12.040816326530601,
 12.448979591836737,
 12.857142857142838,
 13.265306122448939,
 13.67346938775511,
 14.081632653061211,
 14.489795918367347,
 14.89795918367345,
 15.306122448979586,
 15.714285714285722,
 16.122448979591788,
 16.530612244897924,
 16.93877551020406,
 17.346938775510196,
 17.755102040816332,
 18.1632653061224,
 18.571428571428605,
 18.979591836734674,
 19.38775510204074,
 19.7959183673469

In [6]:
dydx

array([ 0.20408163,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 19.79591837])

In [7]:
y

array([  1.        ,   1.04164931,   1.16659725,   1.37484382,
         1.666389  ,   2.04123282,   2.49937526,   3.04081633,
         3.66555602,   4.37359434,   5.16493128,   6.03956685,
         6.99750104,   8.03873386,   9.16326531,  10.37109538,
        11.66222407,  13.0366514 ,  14.49437734,  16.03540192,
        17.65972511,  19.36734694,  21.15826739,  23.03248646,
        24.99000416,  27.03082049,  29.15493544,  31.36234902,
        33.65306122,  36.02707205,  38.48438151,  41.02498959,
        43.64889629,  46.35610162,  49.14660558,  52.02040816,
        54.97750937,  58.0179092 ,  61.14160766,  64.34860475,
        67.63890046,  71.01249479,  74.46938776,  78.00957934,
        81.63306955,  85.33985839,  89.12994586,  93.00333195,
        96.96001666, 101.        ])

In [8]:
help(np.gradient)

Help on function gradient in module numpy:

gradient(f, *varargs, **kwargs)
    Return the gradient of an N-dimensional array.
    
    The gradient is computed using second order accurate central differences
    in the interior points and either first or second order accurate one-sides
    (forward or backwards) differences at the boundaries.
    The returned gradient hence has the same shape as the input array.
    
    Parameters
    ----------
    f : array_like
        An N-dimensional array containing samples of a scalar function.
    varargs : list of scalar or array, optional
        Spacing between f values. Default unitary spacing for all dimensions.
        Spacing can be specified using:
    
        1. single scalar to specify a sample distance for all dimensions.
        2. N scalars to specify a constant sample distance for each dimension.
           i.e. `dx`, `dy`, `dz`, ...
        3. N arrays to specify the coordinates of the values along each
           dimension of

In [25]:
import math as m

def f(x):
    return m.sin(x)

def g(x):
    return np.sin(x)

N, L = 100000, 2 * m.pi
x, dx = np.linspace(0, L, N), L / N

In [30]:
dx

6.283185307179586e-05

In [26]:
diff = []
for i in x:
    diff.append((f(i + dx) - f(i)) / dx)

In [27]:
diff[:10]

[0.9999999993420264,
 0.9999999953941254,
 0.9999999874983037,
 0.9999999756545622,
 0.9999999598628981,
 0.9999999401233157,
 0.9999999164358112,
 0.999999888800388,
 0.9999998572170425,
 0.9999998216857776]

In [33]:
f(x[0])

0.0

In [34]:
f(x[1])

6.283248135526688e-05

In [31]:
g(x)[:10]

array([0.00000000e+00, 6.28324814e-05, 1.25664962e-04, 1.88497443e-04,
       2.51329923e-04, 3.14162402e-04, 3.76994879e-04, 4.39827356e-04,
       5.02659830e-04, 5.65492302e-04])

In [28]:
diff_ = np.gradient(g(x), dx)

In [29]:
diff_[:10]

array([1.00001   , 1.00001   , 1.00000999, 1.00000998, 1.00000997,
       1.00000995, 1.00000993, 1.0000099 , 1.00000987, 1.00000984])

In [37]:
f_= np.vectorize(f)

In [38]:
f_

In [39]:
diff___ = np.gradient(f_(x),dx)

In [40]:
diff___[:10]

array([1.00001   , 1.00001   , 1.00000999, 1.00000998, 1.00000997,
       1.00000995, 1.00000993, 1.0000099 , 1.00000987, 1.00000984])

# 적분 계산

   https://www.tutorialspoint.com/scipy/scipy_integrate.htm